// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class rm_isread_contact : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rm_isread_contact));
        
        string IMigrationMetadata.Id
        {
            get { return "202304100455262_rm_isread_contact"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
