// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class remove_allowhtml_for_messagecontent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_allowhtml_for_messagecontent));
        
        string IMigrationMetadata.Id
        {
            get { return "202304120351284_remove_allowhtml_for_messagecontent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
